<a href="https://colab.research.google.com/github/mks2607/Data_Scientist/blob/mks2607/learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = pd.read_excel("/content/Статистика отправок день_неделя.xlsx", sheet_name= "Розничный клиент_РАСПР (28)") #не могу прочитать этот файл - не понимаю почему, другие могу - а этот нет.

data

,Дата,День недели,Номер недели,Интервал недели,Количество писем,Выручка без доп. услуг,Название консолидатора (ID),Название клиента (ID),Дата поступления,Идентификатор подразделения,...,Количество РПО в ф103,Дата списка,Дата квитанции,Тариф за ед. (без НДС),Дополнительные услуги (без НДС),Количество ЭУВ,Сумма по списку (без НДС),Сумма по списку с учетом скидки(без НДС),В том числе электронных (вспомог. поле),В том числе бумажных (вспомог. поле)
0,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,1,29.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,1,01.01.2024,02.01.2024,"29,00р.",0,0,29.0,29.0,1,0
1,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,3,87.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,3,01.01.2024,02.01.2024,"29,00р.",0,0,87.0,87.0,0,3
2,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,103,6901.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,103,01.01.2024,02.01.2024,"67,00р.",0,0,6901.0,6901.0,103,0
3,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,691,47399.5,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,691,01.01.2024,02.01.2024,"67,00р.",2775,111,50174.5,50174.5,0,691
4,2024-01-02,1900-01-03,1,01.01.2024 - 07.01.2024,32,928.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),02.01.2024,NaN,...,32,02.01.2024,03.01.2024,"29,00р.",0,0,928.0,928.0,32,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,2024-07-13,1900-01-07,28,08.07.2024 - 14.07.2024,5527,408104.5,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),13.07.2024,NaN,...,5527,13.07.2024,14.07.2024,"72,00р.",11400,456,419504.5,419504.5,0,5527
780,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,20,620.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,20,14.07.2024,15.07.2024,"31,00р.",0,0,620.0,620.0,20,0
781,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,190,6212.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,190,14.07.2024,15.07.2024,"31,00р.",0,0,6212.0,6212.0,0,190
782,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,822,59184.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,822,14.07.2024,15.07.2024,"72,00р.",0,0,59184.0,59184.0,822,0
783,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,4735,349894.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,4735,14.07.2024,15.07.2024,"72,00р.",10175,407,360069.0,360069.0,0,4735

In [2]:
data["Номер недели"]
data.iloc[:,[2,20]]

     Номер недели  Сумма по списку с учетом скидки(без НДС)
0               1                                      29.0
1               1                                      87.0
2               1                                    6901.0
3               1                                   50174.5
4               1                                     928.0
..            ...                                       ...
779            28                                  419504.5
780            28                                     620.0
781            28                                    6212.0
782            28                                   59184.0
783            28                                  360069.0

[784 rows x 2 columns]

In [3]:
data['Дни недели ENG']=pd.to_datetime(data['Дата']).dt.strftime('%a')
data['Дни недели ENG']

0      Mon
1      Mon
2      Mon
3      Mon
4      Tue
      ...
779    Sat
780    Sun
781    Sun
782    Sun
783    Sun
Name: Дни недели ENG, Length: 784, dtype: object

In [4]:
data[data['Номер недели']==1].iloc[:,20].sum()

1444289.5

In [5]:
df = pd.DataFrame({})
df['День недели'] = pd.to_datetime(data['День недели'])
week_days = list(set(df['День недели']))

In [6]:
df = pd.DataFrame({})
df['День недели'] = pd.to_datetime(data['Дата'])
#week_days = list(set(df['День недели']))
pd.to_datetime(df['День недели'].iloc[0]).strftime('%a')

'Mon'

In [7]:
data.iloc[:,20]

0          29.0
1          87.0
2        6901.0
3       50174.5
4         928.0
         ...
779    419504.5
780       620.0
781      6212.0
782     59184.0
783    360069.0
Name: Сумма по списку с учетом скидки(без НДС), Length: 784, dtype: float64

In [8]:
week_days[0]

Timestamp('1900-01-07 00:00:00')

In [9]:
pd.to_datetime(data['Дата']).iloc[:].strftime('%a')

AttributeError: 'Series' object has no attribute 'strftime'

In [10]:
set(data['Дни недели ENG'])

{'Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed'}

In [11]:
sum_wek = {"Номер недели":[],'Пн': [],'Вт': [],'Ср': [],'Чт': [],'Пт': [],'Сб': [],'Вс': [], "Отправки за неделю": []}
#sum_wek = {"Номер недели":[],'Пн': [], "Отправки за неделю": []}

for i in range(1,29):
    sum_wek['Пн'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Mon'))].iloc[:,5].sum())
    sum_wek['Вт'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Tue'))].iloc[:,5].sum())
    sum_wek['Ср'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Wed'))].iloc[:,5].sum())
    sum_wek['Чт'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Thu'))].iloc[:,5].sum())
    sum_wek['Пт'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Fri'))].iloc[:,5].sum())
    sum_wek['Сб'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Sat'))].iloc[:,5].sum())
    sum_wek['Вс'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Sun'))].iloc[:,5].sum())

    sum_wek['Отправки за неделю'].append(data[data['Номер недели']==i].iloc[:,20].sum())
    sum_wek['Номер недели'].append(i)



new_tab =(pd.DataFrame(sum_wek))

In [12]:
new_tab.to_excel('tab_work_1.xlsx')
new_tab

,Номер недели,Пн,Вт,Ср,Чт,Пт,Сб,Вс,Отправки за неделю
0,1,54416.5,149245.0,180111.5,255214.0,300383.5,288728.5,172415.5,1444289.5
1,2,561166.0,1672405.0,1371040.0,1587669.5,1864284.0,389400.5,383445.5,8019385.5
2,3,1949002.5,1896096.0,1858104.5,1656576.5,1457535.0,524253.0,488839.5,10054682.0
3,4,1218449.0,1954521.0,2102756.5,2220276.5,2148131.0,700397.5,575829.0,11164360.5
4,5,2188956.5,2390239.0,2525191.0,2088627.5,1968409.0,387320.0,476617.0,12306460.0
5,6,2183348.0,2137650.5,2108136.0,2073443.5,1913203.5,495954.0,649783.5,11856994.0
6,7,2155161.0,2071473.0,2048751.5,1997672.0,1976481.0,448234.0,466788.5,11446286.0
7,8,2228608.0,2128783.5,2110223.0,2051661.0,437226.5,378211.5,566403.0,10131816.5
8,9,2212633.0,2272927.0,2499406.5,2693225.0,2144517.5,531930.5,500300.0,13155664.5
9,10,2210804.5,2390307.5,2136632.0,2015339.5,283324.0,349074.5,637127.0,10274784.0
10,11,2207407.0,2220197.0,2193838.5,896010.0,3371634.5,478702.5,497905.5,12150845.0
11,12,2323557.5,2261484.5,2434316.0,2243470.0,2243925.5,443431.0,462627.5,12714512.0
12,13,2591399.5,2614334.0,2530615.5,2645394.0,2890635.5,818617.0,1079549.0,15474744.5
13,14,2372433.0,2090502.5,2248262.0,2144956.0,1999284.0,390424.0,494006.0,12030167.5
14,15,2310026.5,2280249.5,1985922.0,1921211.5,2246975.0,551647.5,521890.5,12099022.5
15,16,2209742.0,2182595.0,2200472.0,2186129.0,2158247.0,433584.0,523768.0,12178637.0
16,17,2347347.5,2382032.5,2189645.0,2341031.0,2357180.5,2069744.5,516252.5,14558933.5
17,18,517920.5,658990.5,523690.0,2161642.0,2037267.5,530230.0,389865.5,6982606.0
18,19,2203310.0,2160922.0,2032800.5,324854.0,372880.5,302845.0,450502.5,8032889.5
19,20,2278732.5,2182470.0,2267175.0,2311056.5,2167101.0,506516.5,509531.5,12500733.0
20,21,2356205.0,2289775.5,2328807.5,2354328.0,2253678.5,411359.0,494413.5,12780142.0
21,22,2410130.0,2486441.5,2361239.5,2452782.5,2235235.0,472484.5,424134.0,13124997.0
22,23,2278330.0,2355479.0,2269834.0,2222930.5,2212513.5,434625.0,466921.0,12534083.0
23,24,2188363.0,2435813.0,881723.0,2551017.0,2288080.0,426614.0,470730.0,11523065.0
24,25,2175312.5,2056412.5,2295552.0,2011926.5,2365457.0,404499.5,407901.5,12000861.5
25,26,2150503.5,2667210.0,2432408.0,3009626.0,3147775.0,674719.0,1003323.5,15417065.0
26,27,2204900.0,2186060.0,2347993.5,2292723.5,2233478.5,468814.0,390333.0,12394352.5
27,28,2372447.5,2399396.0,2336520.5,2161078.5,2493587.5,493505.0,415910.0,12929945.0

In [13]:
data

,Дата,День недели,Номер недели,Интервал недели,Количество писем,Выручка без доп. услуг,Название консолидатора (ID),Название клиента (ID),Дата поступления,Идентификатор подразделения,...,Дата списка,Дата квитанции,Тариф за ед. (без НДС),Дополнительные услуги (без НДС),Количество ЭУВ,Сумма по списку (без НДС),Сумма по списку с учетом скидки(без НДС),В том числе электронных (вспомог. поле),В том числе бумажных (вспомог. поле),Дни недели ENG
0,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,1,29.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,01.01.2024,02.01.2024,"29,00р.",0,0,29.0,29.0,1,0,Mon
1,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,3,87.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,01.01.2024,02.01.2024,"29,00р.",0,0,87.0,87.0,0,3,Mon
2,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,103,6901.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,01.01.2024,02.01.2024,"67,00р.",0,0,6901.0,6901.0,103,0,Mon
3,2024-01-01,1900-01-02,1,01.01.2024 - 07.01.2024,691,47399.5,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),01.01.2024,NaN,...,01.01.2024,02.01.2024,"67,00р.",2775,111,50174.5,50174.5,0,691,Mon
4,2024-01-02,1900-01-03,1,01.01.2024 - 07.01.2024,32,928.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),02.01.2024,NaN,...,02.01.2024,03.01.2024,"29,00р.",0,0,928.0,928.0,32,0,Tue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,2024-07-13,1900-01-07,28,08.07.2024 - 14.07.2024,5527,408104.5,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),13.07.2024,NaN,...,13.07.2024,14.07.2024,"72,00р.",11400,456,419504.5,419504.5,0,5527,Sat
780,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,20,620.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,14.07.2024,15.07.2024,"31,00р.",0,0,620.0,620.0,20,0,Sun
781,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,190,6212.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,14.07.2024,15.07.2024,"31,00р.",0,0,6212.0,6212.0,0,190,Sun
782,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,822,59184.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,14.07.2024,15.07.2024,"72,00р.",0,0,59184.0,59184.0,822,0,Sun
783,2024-07-14,1900-01-01,28,08.07.2024 - 14.07.2024,4735,349894.0,Розничный клиент_РАСПР (28),Розничный клиент_РАСПР (28),14.07.2024,NaN,...,14.07.2024,15.07.2024,"72,00р.",10175,407,360069.0,360069.0,0,4735,Sun

In [14]:

def get_sum_week(data,day,day_en,sum_wek_1,i):
  sum_wek_1[day].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== day_en))].iloc[:,5].sum())
  return sum_wek_1



# пробую создать цикл, для того что бы поместить код в одну строчку.

sum_wek_1 = {"Номер недели":[],'Пн': [],'Вт': [],'Ср': [],'Чт': [],'Пт': [],'Сб': [],'Вс': [], "Отправки за неделю": []}
#sum_wek = {"Номер недели":[],'Пн': [], "Отправки за неделю": []}
days = ['Пн','Вт','Ср','Чт','Пт','Сб','Вс']
days_en = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']


for i in range(1,29):
  for day,day_en in zip(days,days_en):
#      sum_wek_1[day].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== day_en))].iloc[:,5].sum())

      sum_wek_1 = get_sum_week(data,day,day_en, sum_wek_1,i)
      #    sum_wek_1['Пн'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== j))].iloc[:,5].sum())
      #    sum_wek['Вт'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Tue'))].iloc[:,5].sum())
      #    sum_wek['Ср'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Wed'))].iloc[:,5].sum())
      #    sum_wek['Чт'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Thu'))].iloc[:,5].sum())
      #    sum_wek['Пт'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Fri'))].iloc[:,5].sum())
      #    sum_wek['Сб'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Sat'))].iloc[:,5].sum())
      #    sum_wek['Вс'].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== 'Sun'))].iloc[:,5].sum())

  sum_wek_1['Отправки за неделю'].append(data[data['Номер недели']==i].iloc[:,20].sum())
  sum_wek_1['Номер недели'].append(i)

new_tab_1 =(pd.DataFrame(sum_wek_1))

new_tab_1
#sum_wek_1['Номер недели']

,Номер недели,Пн,Вт,Ср,Чт,Пт,Сб,Вс,Отправки за неделю
0,1,54416.5,149245.0,180111.5,255214.0,300383.5,288728.5,172415.5,1444289.5
1,2,561166.0,1672405.0,1371040.0,1587669.5,1864284.0,389400.5,383445.5,8019385.5
2,3,1949002.5,1896096.0,1858104.5,1656576.5,1457535.0,524253.0,488839.5,10054682.0
3,4,1218449.0,1954521.0,2102756.5,2220276.5,2148131.0,700397.5,575829.0,11164360.5
4,5,2188956.5,2390239.0,2525191.0,2088627.5,1968409.0,387320.0,476617.0,12306460.0
5,6,2183348.0,2137650.5,2108136.0,2073443.5,1913203.5,495954.0,649783.5,11856994.0
6,7,2155161.0,2071473.0,2048751.5,1997672.0,1976481.0,448234.0,466788.5,11446286.0
7,8,2228608.0,2128783.5,2110223.0,2051661.0,437226.5,378211.5,566403.0,10131816.5
8,9,2212633.0,2272927.0,2499406.5,2693225.0,2144517.5,531930.5,500300.0,13155664.5
9,10,2210804.5,2390307.5,2136632.0,2015339.5,283324.0,349074.5,637127.0,10274784.0
10,11,2207407.0,2220197.0,2193838.5,896010.0,3371634.5,478702.5,497905.5,12150845.0
11,12,2323557.5,2261484.5,2434316.0,2243470.0,2243925.5,443431.0,462627.5,12714512.0
12,13,2591399.5,2614334.0,2530615.5,2645394.0,2890635.5,818617.0,1079549.0,15474744.5
13,14,2372433.0,2090502.5,2248262.0,2144956.0,1999284.0,390424.0,494006.0,12030167.5
14,15,2310026.5,2280249.5,1985922.0,1921211.5,2246975.0,551647.5,521890.5,12099022.5
15,16,2209742.0,2182595.0,2200472.0,2186129.0,2158247.0,433584.0,523768.0,12178637.0
16,17,2347347.5,2382032.5,2189645.0,2341031.0,2357180.5,2069744.5,516252.5,14558933.5
17,18,517920.5,658990.5,523690.0,2161642.0,2037267.5,530230.0,389865.5,6982606.0
18,19,2203310.0,2160922.0,2032800.5,324854.0,372880.5,302845.0,450502.5,8032889.5
19,20,2278732.5,2182470.0,2267175.0,2311056.5,2167101.0,506516.5,509531.5,12500733.0
20,21,2356205.0,2289775.5,2328807.5,2354328.0,2253678.5,411359.0,494413.5,12780142.0
21,22,2410130.0,2486441.5,2361239.5,2452782.5,2235235.0,472484.5,424134.0,13124997.0
22,23,2278330.0,2355479.0,2269834.0,2222930.5,2212513.5,434625.0,466921.0,12534083.0
23,24,2188363.0,2435813.0,881723.0,2551017.0,2288080.0,426614.0,470730.0,11523065.0
24,25,2175312.5,2056412.5,2295552.0,2011926.5,2365457.0,404499.5,407901.5,12000861.5
25,26,2150503.5,2667210.0,2432408.0,3009626.0,3147775.0,674719.0,1003323.5,15417065.0
26,27,2204900.0,2186060.0,2347993.5,2292723.5,2233478.5,468814.0,390333.0,12394352.5
27,28,2372447.5,2399396.0,2336520.5,2161078.5,2493587.5,493505.0,415910.0,12929945.0

In [15]:
def fun(a,b,c):
  d=(a+b)/c
  return d

a_1=[1,2,3]
b_1=[4,5,6]
c_1=[7,8,9]

for (a,b,c) in zip(a_1,b_1,c_1):
  print(a,b,c)
  res =fun(a,b,c)
  print(res)

1 4 7
0.7142857142857143
2 5 8
0.875
3 6 9
1.0

In [16]:
import random

def fun(td,day,h,s):
  tb[day].append(s)
  return tb


tb = {'time':[],'Пн':[],'Вт':[]}
days = ['Пн','Вт']

for h in range(10,18):
  tb['time'].append(f'{h}:00')
  for day in days:
    s= random.randint(1000,2000)
    tb =fun(tb,day,h,s)

pd.DataFrame(tb)

    time    Пн    Вт
0  10:00  1698  1974
1  11:00  1484  1557
2  12:00  1927  1625
3  13:00  1194  1672
4  14:00  1170  1359
5  15:00  1978  1539
6  16:00  1258  1936
7  17:00  1667  1030

In [17]:
for day,day_en in zip(days,days_en):
  print(day,day_en)

Пн Mon
Вт Tue

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [20]:
import pandas as pd
data_1 = pd.read_excel('/content/drive/MyDrive/Список ШПИ(для еженедельного отчета)/3. Март.xlsx')
data_1

,Дата,Тип,Способ доставки,Тип получателя,Тариф,День,Неделя,Количество
0,2024-03-01,заказное,бумажное,ЮЛ,70.5,5,9,1
1,2024-03-01,заказное,бумажное,ЮЛ,70.5,5,9,1
2,2024-03-01,заказное,бумажное,ЮЛ,67.0,5,9,1
3,2024-03-01,заказное,бумажное,ЮЛ,67.0,5,9,1
4,2024-03-01,заказное,бумажное,ФЛ,67.0,5,9,1
...,...,...,...,...,...,...,...,...
786399,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1
786400,2024-03-31,простое,бумажное,ЮЛ,29.0,7,13,1
786401,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1
786402,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1
786403,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1

Warning: total number of rows (786404) exceeds max_rows (20000). Limiting to first (20000) rows.

Объединение таблиц в одну

In [21]:
data_week = pd.concat([data_1,data_1],axis=0)

In [22]:
data_week

,Дата,Тип,Способ доставки,Тип получателя,Тариф,День,Неделя,Количество
0,2024-03-01,заказное,бумажное,ЮЛ,70.5,5,9,1
1,2024-03-01,заказное,бумажное,ЮЛ,70.5,5,9,1
2,2024-03-01,заказное,бумажное,ЮЛ,67.0,5,9,1
3,2024-03-01,заказное,бумажное,ЮЛ,67.0,5,9,1
4,2024-03-01,заказное,бумажное,ФЛ,67.0,5,9,1
...,...,...,...,...,...,...,...,...
786399,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1
786400,2024-03-31,простое,бумажное,ЮЛ,29.0,7,13,1
786401,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1
786402,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1
786403,2024-03-31,простое,бумажное,ФЛ,29.0,7,13,1

In [25]:
data_week.to_csv('/content/drive/MyDrive/Список ШПИ(для еженедельного отчета)/тестовое_объединениею.csv')

In [28]:
import numpy as np
np.unique(data_week['Тип получателя'].values)

array(['ФЛ', 'ЮЛ'], dtype=object)

In [ ]:
data_fl_ul =

In [53]:
#def get_sum_week(data,day,day_en,sum_wek_1,i):
#  sum_wek_1[day].append(data[((data['Номер недели']==i) & (data['Дни недели ENG']== day_en))].iloc[:,5].sum())
# return sum_wek_1


data_fl_ul = {"Номер недели":[],'ФЛ': [],'ЮЛ': [],'Итог': []} # формируем такую таблицу


for i in range(1,29):

  data_fl_ul['Номер недели'].append(i)
  data_fl_ul['ФЛ'].append(data_week[((data_week['Неделя']==i) & (data_week['Тип получателя']=='ФЛ'))].shape[0])
  data_fl_ul['ЮЛ'].append(data_week[((data_week['Неделя']==i) & (data_week['Тип получателя']=='ЮЛ'))].shape[0])
  itog = data_fl_ul['ФЛ'][-1] + data_fl_ul['ЮЛ'][-1]
  if itog == 0:
    data_fl_ul['ФЛ'][-1] = 0
    data_fl_ul['ЮЛ'][-1] = 0
  else:
    data_fl_ul['ФЛ'][-1]=round(data_fl_ul['ФЛ'][-1]/itog*100,2)
    data_fl_ul['ЮЛ'][-1]=round(data_fl_ul['ЮЛ'][-1]/itog*100,2)

  data_fl_ul['Итог'].append(data_fl_ul['ФЛ'][-1] + data_fl_ul['ЮЛ'][-1])




new_tab_1 =(pd.DataFrame(data_fl_ul))

new_tab_1
#sum_wek_1['Номер недели']

    Номер недели     ФЛ      ЮЛ   Итог
0              1   0.00  100.00  100.0
1              2  38.10   61.90  100.0
2              3  31.82   68.18  100.0
3              4  23.81   76.19  100.0
4              5  31.25   68.75  100.0
5              6  37.50   62.50  100.0
6              7  16.22   83.78  100.0
7              8  22.86   77.14  100.0
8              9  22.81   77.19  100.0
9             10  24.03   75.97  100.0
10            11  22.75   77.25  100.0
11            12  22.68   77.32  100.0
12            13  19.15   80.85  100.0
13            14   0.00    0.00    0.0
14            15   0.00    0.00    0.0
15            16   0.00    0.00    0.0
16            17   0.00    0.00    0.0
17            18   0.00    0.00    0.0
18            19   0.00    0.00    0.0
19            20   0.00    0.00    0.0
20            21   0.00    0.00    0.0
21            22   0.00    0.00    0.0
22            23   0.00    0.00    0.0
23            24   0.00    0.00    0.0
24            25   0.00    0.00    0.0
25            26   0.00    0.00    0.0
26            27   0.00  100.00  100.0
27            28   0.00  100.00  100.0

In [33]:
data_week.iloc[:,3]

0         ЮЛ
1         ЮЛ
2         ЮЛ
3         ЮЛ
4         ФЛ
          ..
786399    ФЛ
786400    ЮЛ
786401    ФЛ
786402    ФЛ
786403    ФЛ
Name: Тип получателя, Length: 1572808, dtype: object

In [46]:
data_week[((data_week['Неделя']==1) & (data_week['Тип получателя']=='ЮЛ'))].iloc[:,3].shape[0]

4

In [43]:
data_week[((data_week['Неделя']==9) & (data_week['Тип получателя']=='ЮЛ'))].shape[0]

73350

In [47]:
data_week[(data_week['Неделя']==1)]

,Дата,Тип,Способ доставки,Тип получателя,Тариф,День,Неделя,Количество
462,2024-01-06,заказное,бумажное,ЮЛ,70.5,6,1,1
28200,2024-01-02,заказное,бумажное,ЮЛ,67.0,2,1,1
462,2024-01-06,заказное,бумажное,ЮЛ,70.5,6,1,1
28200,2024-01-02,заказное,бумажное,ЮЛ,67.0,2,1,1