<a href="https://colab.research.google.com/github/mks2607/Data_Scientist/blob/mks2607/Marvel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/Marvel Vs DC NEW.csv')

In [4]:
df

,ID,Movie,Year,Genre,RunTime,Description,IMDB_Score
0,0,Eternals,-2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0
1,1,Loki,(2021– ),"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0
2,2,The Falcon and the Winter Soldier,-2021,"Action,Adventure,Drama",50 min,"Following the events of 'Avengers: Endgame,' S...",7.5
3,3,WandaVision,-2021,"Action,Comedy,Drama",350 min,Blends the style of classic sitcoms with the M...,8.1
4,4,Spider-Man: No Way Home,-2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0
...,...,...,...,...,...,...,...
1685,1685,DC's Legends of Tomorrow,(2016– ),"Action,Adventure,Drama",42 min,"Worlds lived, worlds died. Nothing will ever b...",8.5
1686,1686,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,"In the wake of Lex Luthor's return, the show f...",8.3
1687,1687,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara comes face to face with Red Daughter and ...,8.1
1688,1688,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara and Lena head to Kaznia to hunt down Lex....,7.4
1689,1689,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Supergirl must deal with the destructive after...,7.5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           1690 non-null   int64
 1   Movie        1690 non-null   object
 2   Year         1657 non-null   object
 3   Genre        1683 non-null   object
 4   RunTime      1690 non-null   object
 5   Description  1690 non-null   object
 6   IMDB_Score   1690 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 92.5+ KB

In [44]:
df.groupby('Genre').sum().head(5)

TypeError: can only concatenate str (not "int") to str

In [23]:
import numpy as np

In [32]:
df = df.fillna(0)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           1690 non-null   int64
 1   Movie        1690 non-null   object
 2   Year         1690 non-null   object
 3   Genre        1690 non-null   object
 4   RunTime      1690 non-null   object
 5   Description  1690 non-null   object
 6   IMDB_Score   1690 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 92.5+ KB

In [35]:
df['RunTime'] = df['RunTime'].str.replace(r'[a-zA-Z]','', regex=True)

In [36]:
df

,ID,Movie,Year,Genre,RunTime,Description,IMDB_Score
0,0,Eternals,-2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0
1,1,Loki,(2021– ),"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0
2,2,The Falcon and the Winter Soldier,-2021,"Action,Adventure,Drama",50,"Following the events of 'Avengers: Endgame,' S...",7.5
3,3,WandaVision,-2021,"Action,Comedy,Drama",350,Blends the style of classic sitcoms with the M...,8.1
4,4,Spider-Man: No Way Home,-2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0
...,...,...,...,...,...,...,...
1685,1685,DC's Legends of Tomorrow,(2016– ),"Action,Adventure,Drama",42,"Worlds lived, worlds died. Nothing will ever b...",8.5
1686,1686,Supergirl,(2015–2021),"Action,Adventure,Drama",42,"In the wake of Lex Luthor's return, the show f...",8.3
1687,1687,Supergirl,(2015–2021),"Action,Adventure,Drama",42,Kara comes face to face with Red Daughter and ...,8.1
1688,1688,Supergirl,(2015–2021),"Action,Adventure,Drama",42,Kara and Lena head to Kaznia to hunt down Lex....,7.4
1689,1689,Supergirl,(2015–2021),"Action,Adventure,Drama",42,Supergirl must deal with the destructive after...,7.5

In [37]:
df['RunTime'] = df['RunTime'].astype(int)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           1690 non-null   int64
 1   Movie        1690 non-null   object
 2   Year         1690 non-null   object
 3   Genre        1690 non-null   object
 4   RunTime      1690 non-null   int64
 5   Description  1690 non-null   object
 6   IMDB_Score   1690 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 92.5+ KB

In [52]:
df_int = df.groupby('Genre').sum('RunTime')

df_int.info()

<class 'pandas.core.frame.DataFrame'>
Index: 91 entries, 0 to Talk-Show
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          91 non-null     int64
 1   RunTime     91 non-null     int64
 2   IMDB_Score  91 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 2.8+ KB

In [53]:
df_int

                            ID  RunTime  IMDB_Score
Genre
0                         3619      120        17.4
Action                     455        0         6.6
Action,Adventure          1635      551        29.5
Action,Adventure,Comedy  28064     1711       174.4
Action,Adventure,Crime   36519     1483       252.1
...                        ...      ...         ...
Short,Adventure,Sci-Fi     559       12         8.1
Short,Comedy,Fantasy        63        4         8.1
Short,Comedy,Music          49        4         8.1
Short,Sci-Fi               176       29        13.5
Talk-Show                 1531       82         0.0

[91 rows x 3 columns]

In [64]:
df_int[df_int['ID'] == 455]

         ID  RunTime  IMDB_Score
Genre
Action  455        0         6.6